defmodule Mix.Tasks.Invader.Gen.Env do
  @moduledoc """
  Generates a .env file with required secrets for local development.

  If .env already exists, only missing secrets will be added.

      $ mix invader.gen.env

  ## Generated secrets

    * `CLOAK_KEY` - Encryption key for sensitive data
    * `TOKEN_SIGNING_SECRET` - Secret for signing authentication tokens
    * `ADMIN_SETUP_TOKEN` - Token required for first admin signup

  ## GitHub OAuth

  You still need to manually add GitHub OAuth credentials:

    1. Create an OAuth App at https://github.com/settings/applications/new
    2. Set Homepage URL to: http://localhost:4000
    3. Set Callback URL to: http://localhost:4000/auth/user/github/callback
    4. Add GITHUB_CLIENT_ID and GITHUB_CLIENT_SECRET to .env
  """

  use Mix.Task

  @env_file ".env"
  @required_secrets ["CLOAK_KEY", "TOKEN_SIGNING_SECRET", "ADMIN_SETUP_TOKEN"]

  @shortdoc "Generates .env file with required secrets"
  def run(_args) do
    existing = read_existing_env()
    missing = find_missing_secrets(existing)

    if Enum.empty?(missing) do
      Mix.shell().info("All required secrets already exist in #{@env_file}")
    else
      new_secrets = generate_secrets(missing)
      write_env(existing, new_secrets)

      Mix.shell().info("")
      Mix.shell().info("Generated secrets in #{@env_file}:")

      for {key, _value} <- new_secrets do
        Mix.shell().info("  - #{key}")
      end

      if is_nil(existing["GITHUB_CLIENT_ID"]) do
        Mix.shell().info("")
        Mix.shell().info("Next steps:")
        Mix.shell().info("  1. Create a GitHub OAuth App at:")
        Mix.shell().info("     https://github.com/settings/applications/new")
        Mix.shell().info("")
        Mix.shell().info("  2. Use these settings:")
        Mix.shell().info("     Homepage URL: http://localhost:4000")
        Mix.shell().info("     Callback URL: http://localhost:4000/auth/user/github/callback")
        Mix.shell().info("")
        Mix.shell().info("  3. Add to .env:")
        Mix.shell().info("     GITHUB_CLIENT_ID=<your-client-id>")
        Mix.shell().info("     GITHUB_CLIENT_SECRET=<your-client-secret>")
        Mix.shell().info("")
        Mix.shell().info("  4. Run: source .env && mix phx.server")
      end
    end
  end

  defp read_existing_env do
    if File.exists?(@env_file) do
      @env_file
      |> File.read!()
      |> String.split("\n", trim: true)
      |> Enum.reject(&String.starts_with?(&1, "#"))
      |> Enum.map(&String.split(&1, "=", parts: 2))
      |> Enum.filter(&(length(&1) == 2))
      |> Enum.map(fn [k, v] -> {String.trim(k), String.trim(v)} end)
      |> Map.new()
    else
      %{}
    end
  end

  defp find_missing_secrets(existing) do
    Enum.reject(@required_secrets, &Map.has_key?(existing, &1))
  end

  defp generate_secrets(missing) do
    Enum.map(missing, fn key ->
      {key, generate_secret(key)}
    end)
  end

  defp generate_secret("ADMIN_SETUP_TOKEN") do
    32
    |> :crypto.strong_rand_bytes()
    |> Base.encode16(case: :lower)
    |> String.slice(0, 32)
  end

  defp generate_secret(_key) do
    32
    |> :crypto.strong_rand_bytes()
    |> Base.encode64()
  end

  defp write_env(_existing, new_secrets) do
    # Preserve existing content
    existing_lines =
      if File.exists?(@env_file) do
        File.read!(@env_file)
      else
        "# Invader Development Environment\n# Generated by: mix invader.gen.env\n"
      end

    # Append new secrets
    new_lines =
      new_secrets
      |> Enum.map(fn {key, value} -> "#{key}=#{value}" end)
      |> Enum.join("\n")

    content =
      if String.ends_with?(existing_lines, "\n") do
        existing_lines <> new_lines <> "\n"
      else
        existing_lines <> "\n" <> new_lines <> "\n"
      end

    File.write!(@env_file, content)
  end
end
