defmodule Invader.Repo.Migrations.AddTelegramPendingPrompts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:telegram_pending_prompts, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :status, :text, null: false
      add :response_text, :text
      add :mission_id, :uuid
      add :timeout_at, :utc_datetime, null: false
      add :caller_pid, :binary
      add :message_id, :bigint, null: false
      add :chat_id, :bigint, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:telegram_pending_prompts)
  end
end