defmodule Invader.Repo.Migrations.AddWorkflows do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:workflows, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :layout_data, :map
      add :status, :text, null: false
      add :description, :text
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:workflows, [:name], name: "workflows_unique_name_index")

    create table(:workflow_runs, primary_key: false) do
      add :workflow_id,
          references(:workflows,
            column: :id,
            name: "workflow_runs_workflow_id_fkey",
            type: :uuid
          ),
          null: false

      add :state, :text, null: false
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :finished_at, :utc_datetime
      add :started_at, :utc_datetime
      add :error_message, :text
      add :context, :map
      add :status, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:workflow_nodes, primary_key: false) do
      add :workflow_id,
          references(:workflows,
            column: :id,
            name: "workflow_nodes_workflow_id_fkey",
            type: :uuid
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :is_start, :boolean, null: false
      add :position_y, :float, null: false
      add :position_x, :float, null: false
      add :config, :map
      add :label, :text
      add :node_type, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:workflow_node_executions, primary_key: false) do
      add :mission_id,
          references(:missions,
            column: :id,
            name: "workflow_node_executions_mission_id_fkey",
            type: :uuid
          )

      add :node_id,
          references(:workflow_nodes,
            column: :id,
            name: "workflow_node_executions_node_id_fkey",
            type: :uuid
          ),
          null: false

      add :run_id,
          references(:workflow_runs,
            column: :id,
            name: "workflow_node_executions_run_id_fkey",
            type: :uuid
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :finished_at, :utc_datetime
      add :started_at, :utc_datetime
      add :error_message, :text
      add :result, :map
      add :iteration, :bigint, null: false
      add :status, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:workflow_edges, primary_key: false) do
      add :target_node_id,
          references(:workflow_nodes,
            column: :id,
            name: "workflow_edges_target_node_id_fkey",
            type: :uuid
          ),
          null: false

      add :source_node_id,
          references(:workflow_nodes,
            column: :id,
            name: "workflow_edges_source_node_id_fkey",
            type: :uuid
          ),
          null: false

      add :workflow_id,
          references(:workflows,
            column: :id,
            name: "workflow_edges_workflow_id_fkey",
            type: :uuid
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :max_iterations, :bigint
      add :is_loop_back, :boolean, null: false
      add :condition, :text
      add :label, :text
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `workflow_edges` table without the `workflow_edges_workflow_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `workflow_edges` table without the `workflow_edges_source_node_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `workflow_edges` table without the `workflow_edges_target_node_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:workflow_edges)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `workflow_node_executions` table without the `workflow_node_executions_run_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `workflow_node_executions` table without the `workflow_node_executions_node_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `workflow_node_executions` table without the `workflow_node_executions_mission_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:workflow_node_executions)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `workflow_nodes` table without the `workflow_nodes_workflow_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:workflow_nodes)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `workflow_runs` table without the `workflow_runs_workflow_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:workflow_runs)

    drop_if_exists unique_index(:workflows, [:name], name: "workflows_unique_name_index")

    drop table(:workflows)
  end
end
