defmodule Invader.Repo.Migrations.AddScopePresets do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:scope_presets, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :is_system, :boolean, null: false
      add :scopes, {:array, :text}, null: false, default: []
      add :description, :text
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:scope_presets, [:name], name: "scope_presets_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:scope_presets, [:name], name: "scope_presets_unique_name_index")

    drop table(:scope_presets)
  end
end
