defmodule Invader.Repo.Migrations.AddScopesToLoadouts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:loadouts) do
      add :scopes, {:array, :text}

      add :scope_preset_id,
          references(:scope_presets,
            column: :id,
            name: "loadouts_scope_preset_id_fkey",
            type: :uuid
          )
    end
  end

  def down do
    alter table(:loadouts) do
      remove :scope_preset_id
      remove :scopes
    end

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `loadouts` table without the `loadouts_scope_preset_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."
  end
end
