defmodule Invader.Repo.Migrations.InitialSetup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:waves, primary_key: false) do
      add :mission_id,
          references(:missions, column: :id, name: "waves_mission_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :exit_code, :bigint
      add :output, :text
      add :finished_at, :utc_datetime
      add :started_at, :utc_datetime
      add :number, :bigint, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:sprites, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :status, :text
      add :org, :text
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:sprites, [:name], name: "sprites_unique_name_index")

    create table(:saves, primary_key: false) do
      add :mission_id,
          references(:missions, column: :id, name: "saves_mission_id_fkey", type: :uuid)

      add :sprite_id,
          references(:sprites, column: :id, name: "saves_sprite_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :comment, :text
      add :wave_number, :bigint
      add :checkpoint_id, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:missions, primary_key: false) do
      add :state, :text, null: false

      add :sprite_id,
          references(:sprites, column: :id, name: "missions_sprite_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :finished_at, :utc_datetime
      add :started_at, :utc_datetime
      add :error_message, :text
      add :status, :text, null: false
      add :current_wave, :bigint
      add :max_duration, :bigint
      add :max_waves, :bigint
      add :priority, :bigint
      add :prompt_path, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `missions` table without the `missions_sprite_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:missions)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `saves` table without the `saves_sprite_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `saves` table without the `saves_mission_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:saves)

    drop_if_exists unique_index(:sprites, [:name], name: "sprites_unique_name_index")

    drop table(:sprites)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `waves` table without the `waves_mission_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:waves)
  end
end
