defmodule Invader.Repo.Migrations.CreateSavedCredentials do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:saved_credentials, primary_key: false) do
      add :encrypted_api_key, :binary, null: false
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :base_url, :text
      add :name, :text, null: false
      add :provider, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:saved_credentials, [:provider],
             name: "saved_credentials_unique_provider_index"
           )
  end

  def down do
    drop_if_exists unique_index(:saved_credentials, [:provider],
                     name: "saved_credentials_unique_provider_index"
                   )

    drop table(:saved_credentials)
  end
end