defmodule Invader.Repo.Migrations.AddTokenToConnections do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:connections) do
      add :encrypted_token, :binary
    end
  end

  def down do
    alter table(:connections) do
      remove :encrypted_token
    end
  end
end
