defmodule Invader.Repo.Migrations.AddMissionGithubRepos do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:mission_github_repos, primary_key: false) do
      add :mission_id,
          references(:missions,
            column: :id,
            name: "mission_github_repos_mission_id_fkey",
            type: :uuid
          ), null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :path, :text
      add :branch, :text
      add :name, :text, null: false
      add :owner, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `mission_github_repos` table without the `mission_github_repos_mission_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:mission_github_repos)
  end
end