defmodule Invader.Repo.Migrations.AddPendingApprovals do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:pending_approvals, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :decided_at, :utc_datetime
      add :decided_by, :text
      add :status, :text, null: false
      add :timeout_at, :utc_datetime, null: false
      add :callback_data, :text, null: false
      add :caller_pid, :binary
      add :action_details, :map
      add :action_type, :text
      add :scope, :text, null: false
      add :mission_id, :uuid, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:pending_approvals)
  end
end