defmodule Invader.Repo.Migrations.CreateConnections do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:connections, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :private_key, :text
      add :installation_id, :text
      add :app_id, :text
      add :status, :text, null: false
      add :name, :text, null: false
      add :type, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:connections, [:type], name: "connections_unique_type_index")

    create table(:connection_requests, primary_key: false) do
      add :connection_id,
          references(:connections,
            column: :id,
            name: "connection_requests_connection_id_fkey",
            type: :uuid
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :duration_ms, :bigint
      add :result, :map
      add :status, :text, null: false
      add :mode, :text, null: false
      add :command, :text, null: false
      add :sprite_id, :text
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `connection_requests` table without the `connection_requests_connection_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:connection_requests)

    drop_if_exists unique_index(:connections, [:type], name: "connections_unique_type_index")

    drop table(:connections)
  end
end
