defmodule Invader.Repo.Migrations.AddIsAdminToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :is_admin, :boolean, null: false
    end
  end

  def down do
    alter table(:users) do
      remove :is_admin
    end
  end
end
