defmodule Invader.Repo.Migrations.AddSpriteProvisioning do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:missions) do
      add :sprite_name, :text
      add :sprite_auto_created, :boolean
      add :sprite_lifecycle, :text
      add :agent_type, :text
      add :agent_command, :text
      add :agent_provider, :text
      add :agent_base_url, :text
      add :agent_api_key, :text
    end
  end

  def down do
    alter table(:missions) do
      remove :agent_api_key
      remove :agent_base_url
      remove :agent_provider
      remove :agent_command
      remove :agent_type
      remove :sprite_lifecycle
      remove :sprite_auto_created
      remove :sprite_name
    end
  end
end
