defmodule Invader.Repo.Migrations.AddEncryption do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:connections) do
      add :encrypted_private_key, :binary
    end

    # Note: Existing plain-text private_key values will NOT be migrated automatically.
    # After running this migration, any existing connections will need their private_key
    # re-entered through the UI, which will encrypt it properly.
    # The old private_key column is removed to ensure no plain-text secrets remain.

    alter table(:connections) do
      remove :private_key
    end
  end

  def down do
    alter table(:connections) do
      add :private_key, :text
    end

    alter table(:connections) do
      remove :encrypted_private_key
    end
  end
end
