defmodule Invader.Repo.Migrations.AddPromptToMissions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:missions) do
      add :prompt, :text
    end
  end

  def down do
    alter table(:missions) do
      remove :prompt
    end
  end
end
