defmodule Invader.Repo.Migrations.AddApprovalScopes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:missions) do
      add :approval_scopes, {:array, :text}, default: []
    end
  end

  def down do
    alter table(:missions) do
      remove :approval_scopes
    end
  end
end