defmodule Invader.Repo.Migrations.AddTelegramToConnections do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:connections) do
      add :telegram_chat_id, :bigint
      add :telegram_username, :text
      add :encrypted_telegram_bot_token, :binary
      add :encrypted_telegram_webhook_secret, :binary
    end
  end

  def down do
    alter table(:connections) do
      remove :encrypted_telegram_webhook_secret
      remove :encrypted_telegram_bot_token
      remove :telegram_username
      remove :telegram_chat_id
    end
  end
end